### PR TITLE
fix #5 - "Problems with content on about page"

### LINKED ISSUE #5: Problems with content on about page
I recently had someone look at the website and they gave me some advice regarding the about page.

Firstly, they said that having a data table as an image meant that screen readers couldn't understand it. They said that it should instead be a table written in HTML.

Also, they advised that - to keep branding consistent - I should have the DISC logo underneath the data table.

-----

**IMPORTANT NOTE**: You must only change the `about.html` file.

### PR DESCRIPTION
**Pull request by yellows111**
should the orphaned image be deleted?

### CODE REVIEW

**Review by pheonixfirewingz — APPROVED** [review]

**Comment by SamuelJHirst** [comment]
Please indent child elements of the table which you've added.

Also, the orphaned image can be deleted.

Once those changes have been made, this should be good to go.

**Review by SamuelJHirst — CHANGES_REQUESTED** [review]
See above comment.

**Review by yellows111 — COMMENTED** [review]
I have changed the relative problems with the files.

**Review by SamuelJHirst — APPROVED** [review]
Thank you for making the changes.

You may now merge this.

**Pull request merged**
